name: ServerStart

on:
    workflow_dispatch

jobs:
    start:
        runs-on: self-hosted
        timeout-minutes: 5

        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Compile file
            run: |
                mkdir build
                g++ -o build/server.out server.cpp

          - name: Start server
            run: ./build/server.out &


          - name: Stop server
            run: sleep 120 && pkill server.out


        


